defaults:
  - benchmark: finsearchcomp
  - override hydra/job_logging: none
  - _self_  # Allow defining variables at the top of this file


main_agent:
  prompt_class: MainAgentPrompt_GAIA
  llm: 
    provider_class: "ClaudeOpenRouterClient"
    model_name: "anthropic/claude-3.7-sonnet"
    async_client: true
    temperature: 0.3
    top_p: 0.95
    min_p: 0.0
    top_k: -1
    max_tokens: 32000
    openrouter_api_key: "${oc.env:OPENROUTER_API_KEY,???}"
    openrouter_base_url: "${oc.env:OPENROUTER_BASE_URL,https://openrouter.ai/api/v1}"
    openrouter_provider: "anthropic"
    disable_cache_control: false
    keep_tool_result: -1
    oai_tool_thinking: false
  
  tool_config:
    - tool-reasoning

  max_turns: -1  # Maximum number of turns for main agent execution
  max_tool_calls_per_turn: 10  # Maximum number of tool calls per turn
  
  input_process:
    o3_hint: true
  output_process:
    o3_final_answer: true

  openai_api_key: "${oc.env:OPENAI_API_KEY,???}" # used for o3 hints and final answer extraction
  add_message_id: true
  keep_tool_result: -1
  chinese_context: "${oc.env:CHINESE_CONTEXT,false}"


sub_agents:
  agent-worker:
    prompt_class: SubAgentWorkerPrompt
    llm: 
      provider_class: "ClaudeOpenRouterClient"
      model_name: "anthropic/claude-3.7-sonnet"
      async_client: true
      temperature: 0.3
      top_p: 0.95
      min_p: 0.0
      top_k: -1
      max_tokens: 32000
      openrouter_api_key: "${oc.env:OPENROUTER_API_KEY,???}"
      openrouter_base_url: "${oc.env:OPENROUTER_BASE_URL,https://openrouter.ai/api/v1}"
      openrouter_provider: "anthropic"
      disable_cache_control: false
      keep_tool_result: -1
      oai_tool_thinking: false
    
    tool_config:
      - tool-searching
      - tool-image-video
      - tool-reading
      - tool-code
      - tool-audio

    max_turns: -1  # Maximum number of turns for main agent execution
    max_tool_calls_per_turn: 10  # Maximum number of tool calls per turn


# Can define some top-level or default parameters here
output_dir: logs/
data_dir: "${oc.env:DATA_DIR,data}"  # Points to where data is stored
