# config/benchmark/xbench-ds.yaml
defaults:
  - default
  - _self_

name: "xbench-ds"

data:
  data_dir: "${data_dir}/xbench-ds"

execution:
  max_tasks: null  # null means no limit
  max_concurrent: 10
  pass_at_k: 1

openai_api_key: "${oc.env:OPENAI_API_KEY,???}"
